### PR TITLE
Add provider examples and integration tests

### LINKED ISSUE #39: Setup tests for the unifi provider.
The build setup requires some tests before we can publish this to provider. Implement some tests using the Unifi Controller running in a Docker container.

### PR DESCRIPTION
**Pull request by aharter**
This adds a similar setup as the wrapped terraform provider.
Bootstraps a unifi controller during test setup and executes the examples.

Closes #39

### CODE REVIEW

**Comment by aharter** [comment]
I changed the PR into `draft`. I skips the tests with `Skipping: PULUMI_ACCESS_TOKEN is not set`

**Comment by ringods** [comment]
@aharter can you use local login to keep Pulumi state when running tests?

https://www.pulumi.com/docs/reference/cli/pulumi_login/#options

**Comment by aharter** [comment]
I'm forced to set `PULUMI_ACCESS_TOKEN` due to this line https://github.com/pulumi/pulumi/blob/ada82e6fd3740628a0a57543ff61209c6d3da0c6/pkg/testing/integration/program.go#L655
Which is weird IMHO (or at least I do not see the immediate requirement to do so). I opted to set it to a bogus value and set `PULUMI_API` to local file (as opposed to calling `pulumi login --local`).

**Comment by ringods** [comment]
@aharter should I configure this as a bogus Github Actions secret in this repo?

**Comment by aharter** [comment]
@ringods I prefer to have the value hard wired. Since we also overwrite the "API endpoint" variable it is less confusing.
I guess the integration framework could be extended to only look for the token if non-local endpoint is used.

**Review by ringods — APPROVED** [review]

**Comment by joshuaspence** [comment]
FYI I found a simpler method that doesn't require the HTTP bootstrapping: https://github.com/paultyng/terraform-provider-unifi/pull/320

**Comment by aharter** [comment]
@joshuaspence Thanks for letting us know. I will look into it.

**Pull request merged**
